<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Conditions of Use</name>
   <tag></tag>
   <elementGuidId>8c5631f7-5b62-47fe-aa6d-3f1231bd31e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='a-page']/footer/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.nav_a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Conditions of Use&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d7186b8-a27f-4544-9c95-0de306d025d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/help/customer/display.html?ie=UTF8&amp;nodeId=508088&amp;ref_=footer_cou</value>
      <webElementGuid>e2d97896-237c-4022-87e8-0281d4fd49be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_a</value>
      <webElementGuid>f22b0c4c-0057-4f5d-8f05-60fa47299c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Conditions of Use</value>
      <webElementGuid>8fccabb8-8932-475c-b6ef-a46b40646ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-page&quot;)/footer[@class=&quot;nav-bb-footer&quot;]/div[@class=&quot;nav-footer-copyright&quot;]/ul[1]/li[1]/a[@class=&quot;nav_a&quot;]</value>
      <webElementGuid>9d0b39d6-6b56-46d3-adff-03a60e251683</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-page']/footer/div[2]/ul/li/a</value>
      <webElementGuid>5a57378c-496f-416d-bb7f-65272e32b7e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Conditions of Use')]</value>
      <webElementGuid>a711ecca-a076-4c29-93c1-300766fb0f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See the full edit from Shopbop'])[1]/following::a[2]</value>
      <webElementGuid>9b695fae-45ac-4064-844a-84681dee09d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Easy, elevated t-shirts'])[1]/following::a[3]</value>
      <webElementGuid>ccbe8d27-4506-4461-a022-6eb101aeedfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Notice'])[1]/preceding::a[1]</value>
      <webElementGuid>3c332977-81b1-41f6-8c79-cf3f04383b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interest-Based Ads'])[1]/preceding::a[2]</value>
      <webElementGuid>a779729e-354c-426d-adbc-fea268a825cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Conditions of Use']/parent::*</value>
      <webElementGuid>fd868d2c-0916-435a-a782-784bfe0263b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/help/customer/display.html?ie=UTF8&amp;nodeId=508088&amp;ref_=footer_cou')]</value>
      <webElementGuid>7e13696d-abfb-4a14-a7f6-aefb44983ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>af11f4be-c488-482c-bdf3-ae610617e55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/help/customer/display.html?ie=UTF8&amp;nodeId=508088&amp;ref_=footer_cou' and (text() = 'Conditions of Use' or . = 'Conditions of Use')]</value>
      <webElementGuid>6abd08a7-b12e-4aa5-b9ae-69c2b57ad111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
