<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>280814c1-0c86-43c9-8292-e4390dfcde75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-bb-footer-logo']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Amazon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#nav-bb-footer-logo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65064849-8f9b-4546-8e65-3f1bb986c337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/G/01/gno/images/general/backup-logo_blue._CB481621655_.png</value>
      <webElementGuid>3ce475c4-3147-4442-a6fd-ef977d25c443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Amazon</value>
      <webElementGuid>8068c6a4-26f9-4cda-b885-6ed65d73304f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-bb-footer-logo&quot;)/img[1]</value>
      <webElementGuid>bd9fb724-f382-4063-b484-1f3c2d2d290b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='nav-bb-footer-logo']/img</value>
      <webElementGuid>50369d9e-87a5-4275-be03-761ac56c2177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Amazon']</value>
      <webElementGuid>acc45816-6a76-42cb-a3d1-e22e3194aa87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>00c17dc7-2896-4024-bade-d1f2e4b74a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/G/01/gno/images/general/backup-logo_blue._CB481621655_.png' and @alt = 'Amazon']</value>
      <webElementGuid>ec7b9e7f-0a5f-4ea2-8231-22c1bbc36f2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
