<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Leave ad feedback_s-image</name>
   <tag></tag>
   <elementGuidId>91f33c4c-9d33-4822-85ce-36bab4699bd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='46186a27-30ac-4b83-bba1-2c4c929ca235']/div/div/span/div/div/div/span/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\34 6186a27-30ac-4b83-bba1-2c4c929ca235&quot;] > .sg-col-inner > .s-widget-container > span > .puis-card-container > div > .s-product-image-container > .rush-component > .a-link-normal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3b6761f7-7007-47d6-93fd-fb3b64dc277a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-image</value>
      <webElementGuid>7587b0ec-e576-440e-ac12-51a9ce426741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL320_.jpg</value>
      <webElementGuid>215fe8e2-2c5e-4a98-910b-705360cd307f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL320_.jpg 1x, https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL480_QL65_.jpg 1.5x, https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL640_QL65_.jpg 2x, https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL800_QL65_.jpg 2.5x, https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL960_QL65_.jpg 3x</value>
      <webElementGuid>d24ff778-8eb3-422b-ae9e-e1eb55c8222e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>LIVIKEY Smart Watch, Fitness Tracker Watch with Heart Rate Monitor, SpO2, Sleep Tracker, 5ATM Waterproof Smartwatch for Wo...</value>
      <webElementGuid>03cf0985-d54d-4f67-b0e3-7fae57cc4a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>accec463-fc70-4573-a428-3920ca9f24b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-index</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>2940c528-fff4-48d9-965b-ec9a20899f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-latency</name>
      <type>Main</type>
      <value>s-product-image</value>
      <webElementGuid>493f3c19-6e89-4b14-a0b0-5ff12eb85ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-image-source-density</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5232048f-0216-4a2c-949a-2e8b0b1ed6fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;46186a27-30ac-4b83-bba1-2c4c929ca235&quot;)/div[@class=&quot;sg-col-inner&quot;]/div[@class=&quot;s-widget-container s-spacing-small s-widget-container-height-small celwidget slot=MAIN template=SEARCH_RESULTS widgetId=search-results_16&quot;]/span[@class=&quot;a-declarative&quot;]/div[@class=&quot;puis-card-container s-card-container s-overflow-hidden aok-relative puis-expand-height puis-include-content-margin puis puis-v6daxkfasd3zd29kuq5kwrxs48 s-latency-cf-section puis-card-border&quot;]/div[@class=&quot;a-section a-spacing-base&quot;]/div[@class=&quot;s-product-image-container aok-relative s-text-center s-image-overlay-grey puis-image-overlay-grey s-padding-left-small s-padding-right-small puis-spacing-small s-height-equalized puis puis-v6daxkfasd3zd29kuq5kwrxs48&quot;]/span[@class=&quot;rush-component&quot;]/a[@class=&quot;a-link-normal s-no-outline&quot;]/div[@class=&quot;a-section aok-relative s-image-square-aspect&quot;]/img[@class=&quot;s-image&quot;]</value>
      <webElementGuid>6183a4e7-970e-43df-9ce1-2b70001ccbad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='46186a27-30ac-4b83-bba1-2c4c929ca235']/div/div/span/div/div/div/span/a/div/img</value>
      <webElementGuid>bea6e4cd-6f49-4632-9d05-7a40eaf2d6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='LIVIKEY Smart Watch, Fitness Tracker Watch with Heart Rate Monitor, SpO2, Sleep Tracker, 5ATM Waterproof Smartwatch for Wo...']</value>
      <webElementGuid>9b95a3f1-f7d8-402f-bbb9-7878a919e487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/span/div/div/div/span/a/div/img</value>
      <webElementGuid>d83d17c5-3a89-4abc-8def-8a6de1e77821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://m.media-amazon.com/images/I/61BLM8tEYOL._AC_UL320_.jpg' and @alt = 'LIVIKEY Smart Watch, Fitness Tracker Watch with Heart Rate Monitor, SpO2, Sleep Tracker, 5ATM Waterproof Smartwatch for Wo...']</value>
      <webElementGuid>7f1f79b0-c3fa-45f5-9b48-d0cf595f46b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
