<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_India</name>
   <tag></tag>
   <elementGuidId>3b2b62da-072d-4a03-82d5-a00a420c0b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='icp-dropdown_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#icp-dropdown_8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;India&quot;i >> internal:text=&quot;India&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31c72f58-10cd-427b-b6c0-b76f2060fca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>51d93845-d1cc-42c8-968f-8d755bd9e701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>156fd3c3-4913-47e6-bddb-9918b0fae5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48d3ed8a-7e27-4afc-af6d-64333b63e2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>{&quot;stringVal&quot;:&quot;https://www.amazon.in/?ref_=icp_country_from_us&quot;}</value>
      <webElementGuid>79e5aedc-76d4-4eae-a2e0-5e532fc2bf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>icp-dropdown_8</value>
      <webElementGuid>781ef288-6599-4abd-95ef-f80069d61b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-dropdown-link</value>
      <webElementGuid>37aed00e-b019-49f8-a080-951e5dafb905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> India</value>
      <webElementGuid>2d0bc3ad-d579-4cd9-888f-425d5d7c0c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;icp-dropdown_8&quot;)</value>
      <webElementGuid>b60b0ec4-8eba-4fd7-ba2c-80d68b1765d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='icp-dropdown_8']</value>
      <webElementGuid>a3c4a3d8-ed2e-4f02-9827-bc245b2929b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='icp-dropdown-item-8']/a</value>
      <webElementGuid>bb309afb-0c6a-4290-9e1a-304a888039ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'India')]</value>
      <webElementGuid>d22eacb7-b90b-45f6-9907-7bea8e6b9a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to top'])[2]/following::a[9]</value>
      <webElementGuid>cf6afac5-72be-4b2f-98da-6eb5c0f1d638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[3]/following::a[10]</value>
      <webElementGuid>3df4f543-73d8-4764-aa9a-67b73ee3a7e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[12]</value>
      <webElementGuid>34e17ed7-6961-412f-b41e-b6104228252b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/ul/li[9]/a</value>
      <webElementGuid>bf3c4df2-a36a-4663-a111-36745170dd14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'icp-dropdown_8' and (text() = ' India' or . = ' India')]</value>
      <webElementGuid>f545535b-2b93-41b3-86e4-90d05da4ce77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
