<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your Orders_search</name>
   <tag></tag>
   <elementGuidId>38aa5c38-466a-4814-a42f-21be608d825d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchOrdersInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchOrdersInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search all orders&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28a477aa-f996-4e6c-837d-950b0611a219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>e4ef6012-ea6c-462f-bf03-947df1d60fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchOrdersInput</value>
      <webElementGuid>9f1baf36-d8ab-4e48-9e21-a4fbea9a2403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search all orders</value>
      <webElementGuid>3e9c7a0d-0255-4578-a6eb-48006cfbeeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>14fe9640-3a2d-49f7-82ba-e46ca5c0c56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9a3c5c6-6afd-49e5-898b-cf203025697b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12</value>
      <webElementGuid>dbd1b268-db79-4a75-a011-70f3a6475eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search all orders</value>
      <webElementGuid>e0c54c13-92a1-4ab2-95a7-9cefe2f8d607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchOrdersInput&quot;)</value>
      <webElementGuid>8bd8c0bf-9c26-46ff-9c16-10655dfff43d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchOrdersInput']</value>
      <webElementGuid>b0b40df7-abfe-49b3-af1b-b3deb358ac8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='a-page']/section/div/div[2]/div[2]/div/form/div/div/input</value>
      <webElementGuid>86eee765-3d3a-4612-9931-c20218658908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/form/div/div/input</value>
      <webElementGuid>e474512a-69a4-4c9a-a3a2-4c8f99cfe613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'searchOrdersInput' and @placeholder = 'Search all orders' and @name = 'search']</value>
      <webElementGuid>9e12c92d-0c9f-4a35-b442-0f492b7e39fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
